"""Make ip_address nullable and update passing_unit_tests default

Revision ID: 966c3dcc1481
Revises: f7ac8c2e2087
Create Date: 2025-07-25 20:31:03.602468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966c3dcc1481'
down_revision: Union[str, Sequence[str], None] = 'f7ac8c2e2087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
