"""Make ip_address nullable and update passing_unit_tests default

Revision ID: f7ac8c2e2087
Revises: 1b430bc0d9ba
Create Date: 2025-07-25 20:24:15.965617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ac8c2e2087'
down_revision: Union[str, Sequence[str], None] = '1b430bc0d9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
